
name: "gin-cli"
mode: "dev"
port: 8088
version: "1.0.1"
log:
  level: "debug"
  filename: "gin_cli.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "Admin123456"
  dbname: "rush_cli_dev"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100